### ISSUE TITLE
torchsearchsorted on CUDA

### ISSUE THREAD

**Issue by ai1361720220000** [krrish94/nerf-pytorch#18]
hello, i have installed torchsearchsorted1.1, but when the code comes to error when running
inds = torchsearchsorted.searchsorted(cdf, u, side="right")

Exception: torchsearchsorted on CUDA device is asked, but it seems that it is not available. Please install it.

**Comment by krrish94** [comment]
Pytorch 1.6 now includes a torchsearchsorted module (which also works on the CPU)

I'd recommend trying that out instead :)

**Comment by ai1361720220000** [comment]
thank you~ i will try it.

**Comment by Ilya-Muromets** [comment]
https://pytorch.org/docs/stable/generated/torch.searchsorted.html

Any reason to hold on to the external searchsorted dependency? 
Might be easier to swap in the official and require pytorch>=1.6

**Comment by krrish94** [comment]
@Ilya-Muromets no reason at all :)

Just that I haven't been able to get back to working on this repo since I published it

**Comment by krrish94** [comment]
Should be an easy PR if anyone's willing to volunteer

**Comment by Ilya-Muromets** [comment]
Made a PR, was just a 2 line change.
Didn't test numerical equivalence, but training 'looks fine'.

**Lego example:**
![image](https://user-images.githubusercontent.com/22484429/100489976-ce329e80-30e5-11eb-941d-7cc53d588c77.png)

**Comment by Jia-Wei-Liu** [comment]
Hi, 
Thanks for sharing your code. I install the pytorch 1.60 but still have the same problem: Exception: torchsearchsorted on CUDA device is asked, but it seems that it is not available. Please install it.
When I try to install torchsearchsorted, it shows Requirement already satisfied.
Can anyone help me? Thank you very much!
Best regards!
